service: rf-mir-lambda

plugins:
  - serverless-vault-plugin
  - serverless-plugin-scripts

custom:
  config: ${file(env/${opt:stage}.yml)}

  vault:
    token: ${env:TOKEN_VAULT}
    url: "https://localhost:8200"
    secret: ${self:custom.config.SecretVaultPath}
    ssl_check: false
  kms:
    keyId: ${env:KEY_KMS_ID}

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment: ${self:custom.config.environmentVars}

functions:
  hello:
    handler: handler.hello

package:
  include:
    - handler.py

  exclude:
    - '**/*'
