service: serverless-vault-plugin

plugins:
  - serverless-vault-plugin
  - serverless-plugin-scripts

custom:
  config: ${file(env/${opt:stage}.yml)}

  vault:
    #token: ${env:TOKEN_VAULT}
    role_id: ${env:TOKEN_VAULT}
    secret_id: "0707be04-ec76-26e2-7c3c-f91246559a79"
    method: "approle"
    url: "http://localhost:8200"
    secret: ${self:custom.config.SecretVaultPath}
    ssl_check: false
    version: "v2"
  kms:
    keyId: ${env:KEY_KMS_ID}

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: ${self:custom.config.environmentVars}

functions:
  hello:
    handler: handler.hello

package:
  include:
    - handler.py

  exclude:
    - '**/*'
