defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/node:stretch
      environment:
      - DISPLAY: :99

version: 2.0

jobs:
  install_and_build:
    <<: *defaults
    working_directory: ~/serverless-vault-plugin
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: npm i
      - run:
          name: CodeStyle
          command: |
            npm run lint
      - run:
          name: Test 
          command: npm run test
      - persist_to_workspace:
          root: ~/serverless-vault-plugin
          paths:
            - .
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/


workflows:
  version: 2

  build-only:
    jobs:
      - install_and_build
